export enum EnumTerpenes {
  MYRCENE = 'Myrcene',
  LIMONENE = 'Limonene',
  CARYOPHYLLENE = 'Caryophyllene',
  TERPINOLENE = 'Terpinolene',
  PINENE = 'Pinene',
  LINALOOL = 'Linalool',
  HUMULENE = 'Humulene',
  OCIMENE = 'Ocimene',
  BISABOLOL = 'Bisabolol',
  CAMPHENE = 'Camphene',
  CARENE = 'Carene',
  EUCALYPTOL = 'Eucalyptol',
  GERANIOL = 'Geraniol',
  ISOPULEGOL = 'Isopulegol',
  NEROLIDOL = 'Nerolidol',
  PHYTOL = 'Phytol',
  TERPINEOL = 'Terpineol',
  VALANCENE = 'Valencene',
  BORNEOL = 'Borneol',
  SABINENE = 'Sabinene'
}
